apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-app-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: devops-app
  namespaceSelector:
    matchNames:
      - devops
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
